name: "Steamfetch"
description: "Github action that downloads files from applications on Steam"
inputs:
  username:
    description: "Optionally provide Steam account username. If unspecified then we'll log in anonymously"
    required: false
    default: ""
  password:
    description: "Optionally provide Steam account password. If unspecified then we'll log in anonymously"
    required: false
    default: ""
  outDir:
    description: "The directory in which to place the downloaded files"
    required: true
  os:
    description: "Decides which version of the game is downloaded. Possible values are windows, macos, linux"
    required: true
  files:
    description: "Optionally provide an array of files to download. If unspecified all files will be downloaded."
    required: false
    default: ""
  app:
    description: "The id of the application to download"
    required: true
  beta:
    description: "Optionally specify which beta branch to download. Default is Public"
    required: false
    default: "Public"
  beta-password:
    description: "Optionally specify a password for the beta branch"
    required: false
    default: ""
  osarch:
    description: "Target OS architecture to download. Possible values are 32, 64"
    required: true
  loginid:
    description: "Optionally specify a unique login 32bit integer. Required if running multiple instances of this action concurrently, or if you don't want steam friends to get signed out when using a personal account"
    required: false
    default: ""
  language:
    description: "Optionally specify a language. Default is english"
    required: false
    default: "english"
runs:
  using: "composite"
  steps:
    - name: "Setup dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.x"
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    - name: "Download DepotDownloader"
      uses: "suisei-cn/actions-download-file@v1"
      with:
        url: "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.4.5/depotdownloader-2.4.5.zip"
        target: "${{ github.action_path }}/depotdownloader/"
    - run: "unzip ./depotdownloader-2.4.5.zip -d ./"
      working-directory: "${{ github.action_path }}/depotdownloader/"
      shell: bash
    - run: chmod +x $GITHUB_ACTION_PATH/job.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/job.sh
      shell: bash
      working-directory: "${{ github.action_path }}"
      env:
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_OUTDIR: ${{ inputs.outDir }}
        INPUT_OS: ${{ inputs.os }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_APP: ${{ inputs.app }}
        INPUT_BETA: ${{ inputs.beta }}
        INPUT_BETA_PASSWORD: ${{ inputs.beta-password }}
        INPUT_OSARCH: ${{ inputs.osarch }}
        INPUT_LOGINID: ${{ inputs.loginid }}
        INPUT_LANGUAGE: ${{ inputs.language }}