name: "Steamfetch"
description: "Github action that downloads files from applications on Steam"
inputs:
  username:
    description: "Optionally provide Steam account username. If unspecified then we'll log in anonymously"
    required: false
    default: ""
  password:
    description: "Optionally provide Steam account password. If unspecified then we'll log in anonymously"
    required: false
    default: ""
  outDir:
    description: "The directory to download the files to"
    required: true
  os:
    description: "Decides which version of the game is downloaded. Valid options are windows, macos, linux"
    required: true
  files:
    description: "Optionally provide an array of files to download"
    required: false
    default: ""
  app:
    description: "The id of the application to download (aka appid)"
    required: true
  beta:
    description: "Optionally specify which beta branch to download (default is Public)"
    required: false
    default: "Public"
  osarch:
    description: "Target OS architecture to download. Valid options are 32, 64"
    required: true
  loginid:
    description: "Optionally specify a unique login 32bit integer. Required if running multiple instances of this action concurrently, or if you don't want steam friends to get signed out if using a personal account"
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - name: "Clone repository"
      uses: "actions/checkout@v2"
    - name: "Setup dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.x"
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    - name: "Download DepotDownloader"
      uses: "suisei-cn/actions-download-file@v1"
      with:
        url: "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.4.5/depotdownloader-2.4.5.zip"
        target: "${{ github.action_path }}/depotdownloader/"
    - run: "unzip ./depotdownloader-2.4.5.zip -d ./"
      working-directory: "${{ github.action_path }}/depotdownloader/"
      shell: bash
    - run: "${{ github.action_path }}/job.sh"
      shell: bash
      working-directory: "${{ github.action_path }}/depotdownloader/"